-- create or replace view dm_khoa as
-- select r.id        as id,
--        u.id        as user_id,
--        u.username  as username,
--        c.name      as course_name,
--        s.name      as subject_name,
--        r.mid_point as mid_point,
--        r.end_point as end_point,
--        case
--            when r.total < 4 then 'F'
--            when (r.total >= 4 and r.total < 5) then 'D'
--            when (r.total >= 5 and r.total < 6) then 'D+'
--            when (r.total >= 6 and r.total < 6.5) then 'C'
--            when (r.total >= 6.5 and r.total < 7) then 'C+'
--            when (r.total >= 7 and r.total < 7.5) then 'B'
--            when (r.total >= 7.5 and r.total < 8.5) then 'B+'
--            else 'A'
--            end     as diem
-- from result r
--          left join users u on r.student_id = u.id
--          left join course c on r.course_id = c.id
--          left join subject s on r.subject_id = s.id;
-- ;
